INSERT INTO rooms (name, type, description, price_per_night, capacity, image_url, amenities) VALUES
('Suite Presidencial', 'suite', 'Suite de dos pisos pensada para quienes buscan privacidad absoluta sin renunciar a la vista. Desde el ventanal principal se domina el océano al amanecer, mientras el jacuzzi privado en la terraza superior invita a cerrar el día bajo las estrellas. El mayordomo asignado está disponible las 24 horas para coordinar cualquier detalle de tu estadía.', 890.00, 4, '/images/suite-presidencial.jpg', ARRAY['Vista al mar', 'Jacuzzi privado', 'Mayordomo', 'Desayuno incluido']),
('Villa Overwater', 'villa', 'Construida enteramente sobre el agua, esta villa tiene un piso de vidrio en el living que deja ver el arrecife de coral bajo tus pies. La terraza privada baja directo al mar, ideal para nadar o hacer snorkel apenas te levantas. Por las noches, el silencio del océano rodea cada rincón de la villa.', 1250.00, 2, '/images/villa-overwater.jpg', ARRAY['Piso de vidrio', 'Terraza privada', 'Snorkel incluido']),
('Suite Jardín Zen', 'suite', 'Una suite en planta baja diseñada como un refugio de calma, rodeada de jardines privados que amortiguan cualquier ruido exterior. Su piscina de inmersión con cascada de piedra es perfecta para relajarte después de un día largo, y puedes solicitar un servicio de spa a domicilio directamente en tu terraza.', 540.00, 3, '/images/suite-jardin-zen.jpg', ARRAY['Jardín privado', 'Piscina de inmersión', 'Spa a domicilio']),
('Bungalow Familiar', 'bungalow', 'Un espacio amplio pensado para compartir en familia, con dos habitaciones independientes y una sala de estar común donde reunirse al final del día. Está rodeado de palmeras y jardines tropicales, a pasos de las zonas comunes del resort, y el club infantil está incluido para que los más pequeños también tengan su propia aventura.', 620.00, 6, '/images/bungalow-familiar.jpg', ARRAY['Dos habitaciones', 'Sala de estar', 'Club infantil incluido']),
('Suite Skyline', 'suite', 'Ubicada en el piso más alto de la torre principal, esta suite ofrece una vista de 360° que cambia completamente entre el día y la noche. El acceso al lounge exclusivo del último piso está incluido, y el check-in privado significa que nunca tendrás que hacer fila junto a otros huéspedes.', 980.00, 2, '/images/suite-skyline.jpg', ARRAY['Vista 360°', 'Lounge exclusivo', 'Check-in privado']),
('Villa Privada con Piscina', 'villa', 'Completamente independiente del resto del resort, esta villa tiene su propia piscina infinita que parece fundirse con el horizonte. Puedes solicitar un chef personal para preparar cada comida a tu gusto dentro de la propiedad, y cuenta con seguridad privada las 24 horas para que tu estadía sea completamente tranquila.', 1590.00, 5, '/images/villa-privada-piscina.jpg', ARRAY['Piscina infinita', 'Chef personal', 'Seguridad privada']),
('Villa Solstice Marítima', 'villa', 'Situada justo frente al mar, esta villa fue diseñada para disfrutar el atardecer desde su alberca infinita, donde el agua parece continuar hasta el horizonte. El acceso directo a la playa privada está a solo unos pasos de la terraza, ideal para quienes buscan despertar y dormir al ritmo del océano.', 1420.00, 4, '/images/villa-solstice-maritima.jpg', ARRAY['Alberca infinita', 'Frente al mar', 'Terraza al atardecer']),
('Residencia Mirador del Amanecer', 'residencia', 'Ubicada en lo alto de una colina con vista privilegiada al amanecer, esta residencia es ideal para quienes buscan empezar el día con calma. Su terraza de yoga privada mira directo hacia el horizonte, y una chimenea exterior mantiene el ambiente cálido en las noches más frescas.', 1180.00, 4, '/images/mirador-del-amanecer.jpg', ARRAY['Vista panorámica', 'Terraza de yoga', 'Chimenea exterior']),
('Suite Ámbar', 'suite', 'Un espacio íntimo y cálido, pensado para desconectar por completo. La chimenea interior crea un ambiente acogedor incluso en las noches más frías, mientras la tina de cobre junto al ventanal es perfecta para un baño relajante con vista al paisaje. El balcón privado invita a tomar un café en silencio cada mañana.', 760.00, 2, '/images/suite-ambar.jpg', ARRAY['Chimenea interior', 'Tina de cobre', 'Balcón privado']),
('Villa Duna Blanca', 'villa', 'De líneas minimalistas y fachada blanca, esta villa está construida casi al borde de la arena, con acceso directo a una playa privada. Su diseño despejado y luminoso combina perfectamente con la ducha exterior junto al jardín, ideal para refrescarte después de un día de sol y mar.', 1350.00, 6, '/images/villa-duna-blanca.jpg', ARRAY['Playa privada', 'Diseño minimalista', 'Ducha exterior']),
('Penthouse Obsidiana', 'penthouse', 'En lo más alto de la torre principal, este penthouse combina diseño contemporáneo con una vista de 360° sobre todo el resort. Cuenta con un bar privado para recibir invitados y acceso directo al rooftop, perfecto para disfrutar una copa mientras cae la noche sobre el horizonte.', 1050.00, 3, '/images/penthouse-obsidiana.jpg', ARRAY['Vista 360°', 'Bar privado', 'Acceso a rooftop']),
('Residencia Bosque Nativo', 'residencia', 'Rodeada de bosque nativo y alejada del bullicio del resort, esta residencia es un refugio para quienes buscan reconectar con la naturaleza. El spa exterior entre los árboles y la fogata privada por las noches hacen de cada estadía una experiencia íntima, acompañada por senderos privados para explorar el entorno.', 890.00, 5, '/images/residencia-bosque-nativo.jpg', ARRAY['Spa exterior', 'Fogata privada', 'Senderos privados']);
